name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: smptera-format-identifiers-rust
        run: cargo build --verbose --all-targets
      - name: Run tests
        working-directory: smptera-format-identifiers-rust
        run: cargo test --verbose --all-targets
      - name: Lint
        working-directory: smptera-format-identifiers-rust
        run: cargo fmt -- --check